### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by bradsolves** [mohsinoffline/wp-twilio-core#12]
I purchased a license through the Freemiums site, but the license key I received does not work (and the plugin is not available for download). I have contacted every support address that I can find, but I have not heard anything back. Are you able to assist?

**Comment by spartac** [comment]
Hi Brad
Can you please comunicate the email you used to purchase wpsms premium?
Did you try to contact us at support@wpsms.io or livechat on wpsms.io ?
I will assist you.
Cheers

**Comment by bradsolves** [comment]
Thank you very much. I did send an email to support@wpsms.io on 9/2, but I will resend now.

**Comment by bradsolves** [comment]
Any word on this? I resent my email, started a chat, and asked for an email back on the web site. Have you received these messages?

**Comment by bradsolves** [comment]
@spartac  anything further on this? I have not received any communication ...

**Comment by spartac** [comment]
Hi
Sorry for the delay.Your email were dropped in the spam email inbox.I will reply you by email.

**Comment by spartac** [comment]
What was the email you used to purchase the plugin??

**Comment by bradsolves** [comment]
would you please email me directly so that I don't need to post the email publicly?

**Comment by bradsolves** [comment]
@spartac I have not received an email from you - are you able to send me an email so that I can communicate the customer's name/email address?

**Comment by spartac** [comment]
Send me an email to spartac7707@gmail.com ,I will confirm receiving it!

**Comment by bradsolves** [comment]
Thank you - email sent.

**Comment by spartac** [comment]
I replied you :)
